Very rough pass at Hourly API
apearson/southern-company-api pull request #27
Opened 2022-01-29 02:31 UTC by alex-hall

This is a very rough pass at the hourly API. I didn't do things like exception handling, data formatting, or anything really outside of getting the e2e workflow figured out and outputting the result. 

Pushing this up as a draft to gauge interest. This API does require a reference to `servicePointNumber`, which I noticed was in the Account Details API interface, but I didn't see a clean way to reference it, so I just made it an ENV for now. 

Like I said, there is a decent amount of work still to do here but I have tested that this works with some local unit tests i've written.

2022-02-03 20:21 UTC, harrisonhjones commented
Hey Alex, I've got some experience with TS and am a Georgia Power customer so I'd like to help if I can. Do you have an idea of what is left to do?

2022-02-04 15:36 UTC, alex-hall commented
So without having talked to the maintainer @apearson , I'm flying a bit blind. However, here are my thoughts:

## Preamble: 

My ultimate goal is to get this data into HomeAssistant, but I haven't done a ton of research to understand how that might work. I know most of the homeassistant integrations are written in python, so I don't know if that's a barrier to entry or not. I do know that there is a way to just basically run a cron and shove data into HomeAssistants DB directly, bypassing the whole UI and integrations, so I think that's an option. 

I say all of this to help provide context for how the API may need to be designed. 

## Remaining TODOs: 

- Think through API design for this, do some research to see how it pairs up with HomeAssistant
- Decide how much unit testing is to be done. There is no real unit test suite at the moment and it seems like there is no network mocking. This is usually a pretty big sticking point for me, but this isn't my repo. 
- See if we can get more context around `servicePointNumber` and whether it should be derived from an account API or if it's easier to just provide an ENV.

2022-02-04 18:26 UTC, harrisonhjones commented
> My ultimate goal is to get this data into HomeAssistant

Ditto. Would be interested in collaborating on this.

> Think through API design for this, do some research to see how it pairs up with HomeAssistant and make sure it plays nice with the existing APIs

I don't think we should design this to work for homeassistant as they are two separate projects but I do think we should at least keep homeassistant as a potential client in mind.

> Decide how much unit testing is to be done. There is no real unit test suite at the moment and it seems like there is no network mocking for the testing that does exist. This is usually a pretty big sticking point for me, but this isn't my repo.

Yea, let's wait for @apearson to chime in on this one

> See if we can get more context around servicePointNumber and whether it should be derived from an account API or if it's easier to just provide an ENV.

Seems reasonable. What about, in lieu of an ENV variable, we pass it as an function argument?

I'm happy to take TODO 1 or 3 as my action item this weekend. Any preference?

2022-02-04 19:14 UTC, alex-hall commented
@harrisonhjones if you could think through todo 1, I’ll do some digging on 3 and if I have Time will put something together for 2

2022-02-04 19:16 UTC, harrisonhjones commented
Sounds good to me. Will allocate a few hours this weekend to do some research.

2022-02-04 21:18 UTC, apearson commented
Hey all, 

I have touched HomeAssistant except for running it for a couple days a few years ago.  My setup is all on Node-RED where this library is called from a function node and the data is then passed into my personal database for storage.  

> Think through API design for this, do some research to see how it pairs up with HomeAssistant and make sure it plays nice with the existing APIs

I'm down for any API design that fits well with the javascript (TS) ecosystem even if we need to add an abstraction layer for HA.  Another way we could go about HA integration is to build a CLI interface that HA can cron call and get the results back.  Would this be a direction you'd want to go?

> Decide how much unit testing is to be done. There is no real unit test suite at the moment and it seems like there is no network mocking for the testing that does exist. This is usually a pretty big sticking point for me, but this isn't my repo.

The unit tests I have in the repo are really integration tests that notify me and any other maintainer when SouthernCo has changed their API. In the past SouthernCo has made minor API changes that broke this package.  I don't mind you taking the unit tests in any direction you feel is best as long as the integration tests stay around and are runnable independently. 

> See if we can get more context around servicePointNumber and whether it should be derived from an account API or if it's easier to just provide an ENV.

I remember that when writing the current methods I ran across a way to get the service point number for an account.  I'll have to go dig that back up. It might even be in the code as far as I know.  


Let me know if I can help you with anything and I'm looking forward to getting this merged in. 

- Andrew Pearson

2022-02-06 00:53 UTC, alex-hall commented
> I'm down for any API design that fits well with the javascript (TS) ecosystem even if we need to add an abstraction layer for HA. Another way we could go about HA integration is to build a CLI interface that HA can cron call and get the results back. Would this be a direction you'd want to go?

Looking at the other APIs, I don't think we'll need anything HomeAssistant specific, I was actually thinking we could use the exact same API as the Daily Interface, with the only addition of a temp field being added per hour: 

```
export interface HourlyData{
	accountNumber: string;
	data: {
		date: Date;
		kWh: number | null;
		cost: number | null;
                temp: number <---- Net New
	}[];
```


> The unit tests I have in the repo are really integration tests that notify me and any other maintainer when SouthernCo has changed their API. In the past SouthernCo has made minor API changes that broke this package. I don't mind you taking the unit tests in any direction you feel is best as long as the integration tests stay around and are runnable independently.

Okay, I likely won't mess with them too much then. If I do anything i'll likely just add a unit test specific folder or some other scheme that doesn't interfere with existing tests. 

> I remember that when writing the current methods I ran across a way to get the service point number for an account. I'll have to go dig that back up. It might even be in the code as far as I know.

Yep, I found it!

JFYI @harrisonhjones I added some interface definitions for the new services and did a bit of error handling, all of which is pushed up on this PR.

2022-02-06 01:49 UTC, alex-hall commented
This is ready for review @harrisonhjones @apearson . 

A few notes for the reviewers: 

- You can't call this API for any date `Today - 2 days`, even their UI has this limitation: 
<img width="404" alt="image" src="https://user-images.githubusercontent.com/5599279/152664806-2dc13d82-f137-4108-a185-78efffda0fe5.png">
- typings.d.ts was missing a bracket at the end of the file, hence the huge diff
- There is probably a refactoring opportunity for the JWT header, can this be set globally in the fetch API? 
- I parsed the data object with new Date() in JS, so date parsing is subject to local device timezone. This could be improved
- I bumped a few packages to address npm audit concerns
- I did NOT implement multiple accounts with this API, but I can, LMK

2022-02-07 04:09 UTC, harrisonhjones reviewed
Generally LGTM. Left some comments to improve (imo) code quality.

2022-02-07 04:09 UTC, harrisonhjones commented on src/main.ts
> +		if (graphData) {
What happens if we don't have graphData? When does this occur? Should we throw an error if it is falsey?

2022-02-07 04:09 UTC, harrisonhjones commented on src/main.ts
> +			throw new Error(`Failed to get hourly data: ${response.statusText} with endpoint: ${url}`);
Thoughts on exposing the status code and response body? Could be useful in debugging.

2022-02-07 04:09 UTC, harrisonhjones commented on src/interfaces/general.ts
> +        temp: number
ok, it's the temperature. Maybe we should add the unit (like `kwh`?). Maybe `tempF`. At a minimum let's add a comment. I thought "temp" meant "temporary" on first read.

2022-02-07 04:09 UTC, harrisonhjones commented on src/main.ts
> +		});
Seems like this is duplicated elsewhere. Maybe it makes sense to create a helper `makeApiRequest` that would look like:

```js
private async makeApiRequest(path: string) {
	const response = await fetch("https://customerservice2api.southerncompany.com/api/MyPowerUsage" + path, {
		method: 'GET',
		headers: {
			'Content-Type': 'application/json; charset=UTF-8',
			Authorization: `bearer ${this.jwt}`
		}
	});
	if (response.status !== 200) {
		let body;
		try {
			body = await response.text()
		} catch (err) {
			console.error("failed to read response body");
		}
		throw new Error(`Failed to make API request [Code: ${response.status}: ${response.statusText}] ${url}: ${body}`);
	}
	return await response.json();
}
```

2022-02-07 04:09 UTC, harrisonhjones commented on tsconfig.json
> +		"esModuleInterop": true,
What's this for?

2022-02-07 04:22 UTC, harrisonhjones commented
I did a bit of research on custom components. I'm still not sure how we get them added to the "official" set of components. Are we 'Ok' with a custom component provided via HACS? @alex-hall ? Or it does look like it's possible to add it as an add-on repo without HACS. Any preference?

2022-02-07 14:04 UTC, alex-hall commented on .gitignore
> +.idea
Yeah, I don't feel strongly about this either, my knee jerk reaction is to put all gitignore stuff at the project level to make it device agnostic. I'll defer to @apearson .

2022-02-07 14:09 UTC, alex-hall commented on jest.config.js
> +  collectCoverage: false,
This is a bit of a long-standing jest bug where this config breaks debugging: https://github.com/facebook/jest/issues/5739

I did it so that I could step through the code in test, but I can always move it out to a separate PR for enhanced dev + test environment setup. I get that this is scope creep

2022-02-07 14:11 UTC, alex-hall commented on src/interfaces/general.ts
> +        temp: number
Ah gotcha, yeah I think this should be temperature. I'm not sure if the unit is configurable or not, but that would add some complexity.

2022-02-07 14:12 UTC, alex-hall commented on src/main.ts
> +		});
Yep, I like this. I'll refactor into this. In an ideal world some of this logic would be broken out into separate modules, but I think this makes sense for now.

2022-02-07 14:13 UTC, alex-hall commented on src/main.ts
> +		if (graphData) {
In my testing, this occurs when you select an invalid date range, e.g. From Today - Today OR if you select a date range that is within the N - 2 limitation. There are similar patterns elsewhere in the code, so I mostly followed those

2022-02-07 14:13 UTC, alex-hall commented on tsconfig.json
> +		"esModuleInterop": true,
More jest debugging magic.

2022-02-07 14:15 UTC, alex-hall commented
@harrisonhjones I've responded to most of your review feedback and need a bit of time to implement some of the refactoring and naming. 

As per HomeAssistant, I use HACS personally for a bunch of stuff, so i'm okay with it, do you have a preference one way or another?

2022-02-07 15:10 UTC, apearson commented on .gitignore
> +.idea
I'm okay leaving developer related stuff in the `.gitignore` saves headache down the line for when someone forgets to ignore it on their own `.gitignore`

2022-02-07 15:13 UTC, apearson commented on src/interfaces/general.ts
> +        temp: number
I'm down with `temperature: number` or  `tempF: number`.  I perfer `tempF` but if the temperature might be in C then it's better to settle with `temperature`

2022-02-07 15:14 UTC, apearson commented on src/main.ts
> +			throw new Error(`Failed to get hourly data: ${response.statusText} with endpoint: ${url}`);
Exposing the status code and body in a meaningful way is one of the things I wanted to do with the existing code.

2022-02-07 15:15 UTC, alex-hall commented on src/interfaces/general.ts
> +        temp: number
Just double checked that it doesn't seem like you can change the temperature units in their UI, tempF is probably appropriate.

2022-02-07 15:17 UTC, apearson commented on src/main.ts
> +	private static formatDate(date){
Is there a function in `date-fns` that we can use to do this? 

Maybe? https://date-fns.org/docs/format

2022-02-07 16:00 UTC, alex-hall commented on src/main.ts
> +	private static formatDate(date){
Almost certainly... Let me look into that.

2022-02-07 17:11 UTC, harrisonhjones commented
> As per HomeAssistant, I use HACS personally for a bunch of stuff, so i'm okay with it, do you have a preference one way or another?

I'm still trying to wrap my head around it. I've asked some questions on the [Home Assistant Community Forum](https://community.home-assistant.io/t/difference-between-various-ways-to-add-ons-integrations/389919)

2022-02-07 17:12 UTC, harrisonhjones commented on src/main.ts
> +		});
It _might_ make sense to create this function and use it with the new hourly data function in this PR but migrate the rest of the code to use it in a _separate_ PR.

2022-02-07 17:13 UTC, harrisonhjones commented on src/main.ts
> +			throw new Error(`Failed to get hourly data: ${response.statusText} with endpoint: ${url}`);
Good to hear :) That's why tried to do with the `makeApiRequest`. Still needs to be tested.

2022-02-07 17:17 UTC, harrisonhjones commented on src/main.ts
> +		});
This is probably bikeshedding but maybe play around with the error message a bit to make things clearer. I think I like:

```
`Failed to make API request to ${url}; response: ${response.status} - ${response.statusText} - ${body}`
```

The best. It should render as:

```
Failed to make API request to https://foo.bar; response: 400 - Forbidden - Foo isn't enabled on your Bar
```

Which I think makes it clear what URL is being hit and what the response (body included) was. We _might_ want to quote the body but that might not be necessary.

2022-02-07 17:17 UTC, harrisonhjones commented on tests/data-single.test.ts
> +	const result = await API.getHourlyData(new Date("02/02/2022"), new Date("02/03/2022"))
Maybe add a way to skip this test?

2022-02-07 17:22 UTC, alex-hall commented on tests/data-single.test.ts
> +	const result = await API.getHourlyData(new Date("02/02/2022"), new Date("02/03/2022"))
I just removed it from this PR.

2022-02-07 17:26 UTC, alex-hall commented on src/main.ts
> +		});
> It might make sense to create this function and use it with the new hourly data function in this PR but migrate the rest of the code to use it in a separate PR. 

Yeah I think this is prudent. I started trying to refactor this and ended up rabbit-holing on it. In a branch I have i've basically moved every reference to the jwt token to an `ApiHelper` module, and moved the `loginToken`, `ScWebToken` and `getJWT` token methods to that class.

From there I was going to lazily get the JWT token on the first API call and then cache for future usages, but that's some pretty extreme scope creep. I'll push that branch up and possibly create a separate PR if there is any interest, but for now i'd like to merge this PR without that refactor. Feels like a nice to have. 

I'm also not sure what this does: 

```
			this.emit('connected', accounts);
```

in the SouthernCompanyAPI constructor, but i'm guessing it's trying to get around the whole async await in a constructor limitation.

2022-02-07 17:31 UTC, alex-hall commented
I believe i've addressed all feedback @harrisonhjones @apearson

2022-02-07 18:21 UTC, apearson commented on src/main.ts
> +        const response = await fetch(`https://customerservice2api.southerncompany.com/api/MyPowerUsage/getMPUBasicAccountInformation/${accountNumber}/GPC`, options)
This url ending in GPC seems to be referencing Georgia Power Company.  I'm okay leaving it in for now but making a note to go back and verify this

2022-02-07 18:22 UTC, apearson commented on src/main.ts
> +	private static formatDate(date){
Oh, I meant replace line 88-94 with a `date-fns` function instead of line 84.

2022-02-07 18:26 UTC, apearson commented on src/main.ts
> +		});
```
this.emit('connected', accounts);
```
This line in the constructor is acting like a ready promise and it is a way to get around the async await in constructor limitation.  It emits the `connected` event when the library has retrieved the necessary tokens for making requests.  

This was a way an old way I used to do async library initialization and could be changed to be better.

2022-02-07 19:09 UTC, alex-hall commented on src/main.ts
> +		});
Took a quick stab at a discreet helper class [here](https://github.com/apearson/southern-company-api/pull/28), so i'll mark this conversation as resolved, I want to focus on one thing at a time.

2022-02-07 19:09 UTC, alex-hall commented on src/main.ts
> +	private static formatDate(date){
Sorry about that. Fixed

2022-02-07 20:01 UTC, apearson commented on tests/data-single.test.ts
> +	const result = await API.getHourlyData(new Date("02/02/2022"), new Date("02/03/2022"))
Was this removed? Looks like it's still here

2022-02-07 20:02 UTC, apearson requested changes
Everything looks good to me except for that test.

2022-02-07 20:35 UTC, alex-hall commented
> Everything looks good to me except for that test.

Removed the test

2022-02-07 20:36 UTC, apearson approved these changes
Looks good to me

2022-02-07 21:12 UTC, harrisonhjones approved these changes
LGTM. Left a quick comment about using date-fns somewhere else but not a blocker.

2022-02-07 21:12 UTC, harrisonhjones commented on src/main.ts
>  		return `${date.getMonth() + 1}/${date.getDate()}/${date.getFullYear()} 12:00:00 AM`;
Can we use date-fns here as well? Or would that not make sense?

2022-02-07 22:16 UTC, apearson commented
With no more changes, I'm assuming this is good to be merged?

2022-02-07 22:25 UTC, alex-hall commented
> With no more changes, I'm assuming this is good to be merged?

I don’t have any reservations, but I also haven’t done any E2e testing of all of the APIs, if your node-red workflow still works, that might be enough

2022-02-07 22:26 UTC, apearson commented
@alex-hall Gotcha, I'll do some testing tonight and merge after

2022-02-08 02:06 UTC, merged